import { ITelemetry } from '../..';
import { ArmorDestroy, CarePackageLand, CarePackageSpawn, GameStatePeriodic, ItemAttach, ItemDetach, ItemDrop, ItemEquip, ItemPickup, ItemUnequip, ItemUse, MatchDefinition, MatchEnd, MatchStart, PlayerAttack, PlayerCreate, PlayerKill, PlayerLogin, PlayerLogout, PlayerMakeGroggy, PlayerPosition, PlayerRevive, PlayerTakeDamage, SwimEnd, SwimStart, VehicleDestroy, VehicleLeave, VehicleRide, WheelDestroy } from './events';
export declare class Telemetry {
    private _armorDestroyEvents;
    private _carePackageLandEvents;
    private _carePackageSpawnEvents;
    private _gameStatePeriodicEvents;
    private _itemAttachEvents;
    private _itemDetachEvents;
    private _itemDropEvents;
    private _itemEquipEvents;
    private _itemPickupEvents;
    private _itemUnequipEvents;
    private _itemUseEvents;
    private _matchDefinitionEvents;
    private _matchEndEvents;
    private _matchStartEvents;
    private _playerAttackEvents;
    private _playerCreateEvents;
    private _playerKillEvents;
    private _playerLoginEvents;
    private _playerLogoutEvents;
    private _playerMakeGroggyEvents;
    private _playerPositionEvents;
    private _playerReviveEvents;
    private _playerTakeDamageEvents;
    private _swimEndEvents;
    private _swimStartEvents;
    private _vehicleDestroyEvents;
    private _vehicleLeaveEvents;
    private _vehicleRideEvents;
    private _wheelDestroyEvents;
    constructor(telemetryData: ITelemetry);
    readonly armorDestroyEvents: ArmorDestroy[];
    readonly carePackageLandEvents: CarePackageLand[];
    readonly carePackageSpawnEvents: CarePackageSpawn[];
    readonly gameStatePeriodicEvents: GameStatePeriodic[];
    readonly itemAttachEvents: ItemAttach[];
    readonly itemDetachEvents: ItemDetach[];
    readonly itemDropEvents: ItemDrop[];
    readonly itemEquipEvents: ItemEquip[];
    readonly itemPickupEvents: ItemPickup[];
    readonly itemUnequipEvents: ItemUnequip[];
    readonly itemUseEvents: ItemUse[];
    readonly matchDefinitionEvents: MatchDefinition[];
    readonly matchEndEvents: MatchEnd[];
    readonly matchStartEvents: MatchStart[];
    readonly playerAttackEvents: PlayerAttack[];
    readonly playerCreateEvents: PlayerCreate[];
    readonly playerKillEvents: PlayerKill[];
    readonly playerLoginEvents: PlayerLogin[];
    readonly playerLogoutEvents: PlayerLogout[];
    readonly playerMakeGroggyEvents: PlayerMakeGroggy[];
    readonly playerPositionEvents: PlayerPosition[];
    readonly playerReviveEvents: PlayerRevive[];
    readonly playerTakeDamageEvents: PlayerTakeDamage[];
    readonly swimStartEvents: SwimStart[];
    readonly swimEndEvents: SwimEnd[];
    readonly vehicleDestroyEvents: VehicleDestroy[];
    readonly vehicleLeaveEvents: VehicleLeave[];
    readonly vehicleRideEvents: VehicleRide[];
    readonly wheelDestroyEvents: WheelDestroy[];
}
